# Generated by Django 4.0.5 on 2022-07-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Date',
            field=models.DateTimeField(default=None),
        ),
    ]
