# Generated by Django 4.0.5 on 2022-07-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0002_product_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
